config/routes.rb
Jobgoal::Application.routes.draw do

  get "ameriplan/sales-rep" => 'ameriplan#sales'
  get 'ameriplan/rssfeed'
  get "industry/forestry"
  get "industry/hunting"
  get "industry/automotive"
  get "industry/banking"
  get "industry/computing"
  get "industry/technology"
  get "industry/defense"
  get "industry/energy"
  get "industry/arts"
  get "industry/food"
  get "industry/health"
  get "industry/insurance"
  get "industry/manufacturing"
  get "industry/marketing"
  get "industry/media"
  get "industry/mining"
  get "industry/personal"
  get "industry/biotechnology"
  get "industry/services"
  get "industry/estate"
  get "industry/retail"
  get "industry/transportation"
  get "industry/travel"
  get "industry/waste"
  get "industry/remediation"

  get "states/alabama"
  get "states/alaska"
  get "states/arizona"
  get "states/arkansas"
  get "states/california"
  get "states/colorado"
  get "states/connecticut"
  get "states/delaware"
  get "states/florida"
  get "states/georgia"
  get "states/hawaii"
  get "states/idaho"
  get "states/illinois"
  get "states/indiana"
  get "states/iowa"
  get "states/kansas"
  get "states/kentucky"
  get "states/louisiana"
  get "states/maine"
  get "states/maryland"
  get "states/massachusetts"
  get "states/michigan"
  get "states/minnesota"
  get "states/mississippi"
  get "states/missouri"
  get "states/montana"
  get "states/nebraska"
  get "states/nevada"
  get "states/new_hampshire"
  get "states/new_mexico"
  get "states/new_jersey"
  get "states/new_york"
  get "states/north_carolina"
  get "states/north_dakota"
  get "states/ohio"
  get "states/oklahoma"
  get "states/pennsylvania"
  get "states/rhode_island"
  get "states/south_carolina"
  get "states/south_dakota"
  get "states/tennessee"
  get "states/texas"
  get "states/utah"
  get "states/vermont"
  get "states/virginia"
  get "states/washington"
  get "states/west_virginia"
  get "states/wisconsin"
  get "states/wyoming"

  devise_for :users



  mount RailsAdmin::Engine => '/job_goal_admin', :as => 'rails_admin'


  get 'landing' => 'job#landing'
  get 'home' => 'job#home', as: :home
  get 'contact' => 'job#contact', as: :contact

  root 'job#home'

  get "post_job" => 'job#post_job', as: :post_job



  get 'advanced_search' => 'job#advanced_search', as: :advanced_search
  get 'advanced_search_result' => 'job#advanced_search_result', as: :advanced_search_result

  get 'sorting' => 'job#sorting', as: :sorting
  get 'job_listing' => 'job#job_listing', as: :job_listing


  # Dinamic params

  get "post/:id", to: 'job#show', as: :post
  get "page/:id", to: 'job#show_page', as: :page


  get ':search/:location' => 'job#result' , as: :result, via: [:get]
  get ':search' => 'job#search_result' , as: :search_result, via: [:get]
  get '/location/:location' => 'job#location_result' , as: :location_result, via: [:get]
  get 'job/:search/:location' => 'job#next_result', as: :next_result, via: [:get]
end

app/controllers/job_controller.rb
require 'rubygems'
require 'open-uri'
require 'nokogiri'

class JobController < ApplicationController



  before_action :set_post, only: [:show]
  before_action :set_page, only: [:show_page]

  def landing
    @job_pages = JobPages.all
    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.order_by(order: :desc).limit(3)

    $search = params[:search]
    $location = params[:location]

    session[:search] = params[:search]
    session[:location] = params[:location]

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end

    if params[:location] == ''
      @search_finded = true
      redirect_to search_result_path(params[:search])
    elsif params[:search] == ''
      @search_finded = false
      redirect_to location_result_path(params[:location])
    elsif !params[:search].nil? && !params[:location].nil?
      redirect_to result_path(params[:search],params[:location])
    end

  end


  def search_result
    @job_pages = JobPages.all
    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.order_by(order: :desc).limit(3)

    session[:search] = params[:search]

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end


    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:search].to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @total_result_2 = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil?
      @total_result
    else
      @total_result = @total_result
    end
  end


  def location_result
    @job_pages = JobPages.all
    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.order_by(order: :desc).limit(3)

    session[:location] = params[:location]

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end


    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:location].to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @total_result_2 = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil?
      @total_result
    else
      @total_result = @total_result
    end
  end

  def home
    @job_pages = JobPages.all
    $search = params[:search]
    $location = params[:location]

    session[:search] = params[:search]
    session[:location] = params[:location]

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end

    if session[:search].nil?
      session[:search]=params[:search]
    else
      redirect_to result_path(params[:search],params[:location])
    end
  end

  def result
    @job_pages = JobPages.all
    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.order_by(order: :desc).limit(3)
    @jobpages = JobPages.all

    session[:search] = params[:search]
    session[:location] = params[:location]

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end

    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:search].to_s+"/l-"+session[:location].to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @total_result_2 = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil?
      @total_result
    else
      @total_result = @total_result
    end



  end

  def next_result
    @job_pages = JobPages.all
    session[:search] = params[:search]
    session[:location] = params[:location]


    if params[:page].present?
      @page = params[:page]
    end

    @posts = Post.all.order_by(created_at: :desc).limit(3)

    @advertising = Advertising.all.desc('order').limit(3)

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end

    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:search].to_s+"/l-"+session[:location].to_s+"/pn-"+@page.to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil? || @current_page_count.nil?
      render(text:'404')
    else
      render(text:'lol')
    end

    if @total_result.nil?
      @total_result
    end

  end




  def sorting
    @job_pages = JobPages.all
    if params[:sort_by].present?
      session[:sort_by] =params[:sort_by]
    end

    if params[:miles].present?
      session[:miles] =  params[:miles]
    end

    if params[:job_source].present?
      params[:job_source] = params[:job_source]
    end

    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.desc('order').limit(3)

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end


    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:search].to_s+"/l-"+session[:location].to_s+"/pn-"+session[:page].to_s+"/sb-"+session[:sort_by].to_s+"/mi-"+session[:miles].to_s+"/fsr-"+session[:job_source].to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil?
      @total_result
    else
      @total_result = @total_result
    end

    $page = params[:page]

    if $page.nil?
      $page='1'
    else
      # redirect_to 'http://www.simplyhired.com/k-'+$search+'-jobs.html'
      redirect_to next_result_path
    end
  end

  def advanced_search
    @job_pages = JobPages.all
    session[:search] = params[:search]
    session[:location] = params[:location]
   # With All Words
    #
    #
    #
    if params[:with_all_words].present?
      session[:with_all_words] = params[:with_all_words]+"+"

      if session[:with_all_words].to_s.match(/\s/)
        session[:with_all_words] = session[:with_all_words].to_s.gsub!(" ", "+AND+")
      end

    else
      session[:with_all_words] = ''
    end

    if params[:extract_phrase].present?
      session[:extract_phrase] = params[:extract_phrase]+"+"

      if  session[:extract_phrase].to_s.match(/\s/)
        session[:extract_phrase] =  session[:extract_phrase].to_s.gsub!(" ", "+")
      end

    else
      session[:extract_phrase] = ''
    end

    if params[:extract_phrase_company].present?
      session[:extract_phrase_company] = params[:extract_phrase_company]+"+"

      if session[:extract_phrase_company].to_s.match(/\s/)
        session[:extract_phrase_company] = session[:extract_phrase_company].to_s.gsub!(" ", "+")
      end

    else
      session[:extract_phrase_company] = ''
    end

    if params[:without_words].present?
      session[:without_words] = params[:without_words]+"+"

      if session[:without_words].to_s.match(/\s/)
        session[:without_words] = session[:without_words].to_s.gsub!(" ", "+NOT+")
      end

    else
      session[:without_words] = ''
    end

    if params[:least_one_of_words].present?
      session[:least_one_of_words] = params[:least_one_of_words]+"+"

      if session[:least_one_of_words].to_s.match(/\s/)
        session[:least_one_of_words] = session[:least_one_of_words].to_s.gsub!(" ", "+OR+")
      end
    else
      session[:least_one_of_words] = ''
    end

    if params[:state].present?
      session[:state] = params[:state]+"+"

     # if $least_one_of_words.to_s.match(/\s/)
     #   $least_one_of_words = $least_one_of_words.to_s.gsub!(" ", "+OR+")
     # end
    else
      session[:state] = ''
    end

    if params[:state_city].present?
      session[:state_city] = params[:state_city]+"+"

    # if $least_one_of_words.to_s.match(/\s/)
    #   $least_one_of_words = $least_one_of_words.to_s.gsub!(" ", "+OR+")
    # end

    if session[:state_city].to_s.match(/\s/)
      session[:state_city] = session[:state_city].to_s.gsub!(" ", "+")
    end
  else
    session[:state_city] = ''
  end

    if params[:state_zip].present?
      session[:state_zip] = params[:state_zip]+"+"

      # if $least_one_of_words.to_s.match(/\s/)
      #   $least_one_of_words = $least_one_of_words.to_s.gsub!(" ", "+OR+")
      # end

      if session[:state_zip].to_s.match(/\s/)
        session[:state_zip] = session[:state_zip].to_s.gsub!(" ", "+")
      end
    else
      session[:state_zip] = ''
    end

    if params[:miles].present?
      session[:miles] = params[:miles]

    else
      session[:miles] = ''
    end

    if params[:result_per_page].present?
      session[:result_per_page] = params[:result_per_page]

      else
        session[:result_per_page] = ''
      end

    if params[:sort_by_adv].present?
      session[:sort_by_adv] = params[:sort_by_adv]

    else
      session[:sort_by_adv] = ''
    end

app/helpers/job_helper.rb
module JobHelper
end

app/views/job/partials/_advertising.html.haml
- @advertising.each do |ad|
  .content_inner-block1
    =link_to simple_format(ad.link, {}, sanitize: false).to_s.gsub!('<p>','').gsub!('</p>',''), target: '_blank' do
      %h3
        = ad.title
    .location
      %p.grey-light=simple_format(ad.company, {}, sanitize: false).to_s.gsub!('<p>','').gsub!('</p>','') + ' - ' + simple_format(ad.city, {}, sanitize: false).to_s.gsub!('<p>','').gsub!('</p>','')
    %p.text=simple_format(ad.text, {}, sanitize: false).to_s.gsub!('<p>','').gsub!('</p>','')
    .time-ago
      %p.grey-light
        =  time_ago_in_words(ad.created_at)
        ago
        %span.grey-middle= "from " + simple_format(ad.company, {}, sanitize: false).to_s.gsub!('<p>','').gsub!('</p>','')

app/views/job/partials/_footer.html.haml
%footer
  .width960.row.footer_inner2
    .large-6.medium-6.small-6.columns
      %nav
        %ul.first_5_black
          %li
            =link_to  'Home', root_path
          %li
            =link_to  'Post a job', post_job_path
          %li
            =link_to  'Contact Us', contact_path
          %li
          - @job_pages.each do |page|
            %li
              =link_to  page.title, page_path(page)
    .large-6.medium-6.small-6.columns.socials
      =link_to  image_tag('twitter.png'), 'https://twitter.com/JobGoalNet'
      =link_to  image_tag('facebook.png'), 'https://www.facebook.com/jobgoal.net'
      =link_to  image_tag('linkedin.png'), 'https://www.linkedin.com/company/jobgoal-net'
      =link_to  image_tag('google.png'), 'https://plus.google.com/114786001526410880690'
      .fb-like{"data-action" => "like", "data-href" => "http://jobgoal.net", "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"}
      %br
      %br
      .row
        .large-12.medium-12.small-12.columns
          %a{href: "http://secure.trust-guard.com/security/9293", name: "trustlink", onclick: "var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; window.open(this.href.replace(/https?/, 'https'),'welcome','location='+nonwin+',scrollbars=yes,width=517,height='+screen.availHeight+',menubar=no,toolbar=no'); return false;", oncontextmenu: "var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by trust-guard \\251 '+d.getFullYear()+'.'); return false;", rel: "nofollow", target: "_blank"}
            %img{alt: "Security Seals", name: "trustseal", src: "//dw26xg4lubooo.cloudfront.net/seals/logo/9293-header.gif", style: "border: 0;"}/
          %a{href: "http://secure.trust-guard.com/privacy/9293", name: "trustlink", onclick: "var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; window.open(this.href.replace(/https?/, 'https'),'welcome','location='+nonwin+',scrollbars=yes,width=517,height='+screen.availHeight+',menubar=no,toolbar=no'); return false;", oncontextmenu: "var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by trust-guard \\251 '+d.getFullYear()+'.'); return false;", rel: "nofollow", target: "_blank"}
            %img{alt: "Privacy Seals", name: "trustseal", src: "//dw26xg4lubooo.cloudfront.net/seals/privacy/9293-header.gif", style: "border: 0;"}/
        .large-12.medium-12.small-12.columns
          .copyright.right
            %p
              %span © 2014 JobGoal.net
              %br All Rights Reserved

app/views/job/partials/_header.html.haml
%header#mobile_head
  .width960.row
    .large-2.medium-2.small-2.columns.logo
      =link_to image_tag('logo.png'), root_path
    .large-10.medium-10.small-10.columns
      = form_tag landing_path, :method => 'get', :id => "search", :class=>'search-block right ' do
        = text_field_tag :search, params[:search], class: 'search-field', placeholder: "Job Title"
        = text_field_tag :location, params[:location], class: 'search-field', placeholder: "Location (ZIP, city etc)"
        = submit_tag "Search", :name => nil, id: 'search'
    .clear-both
.full-width_bg2#desktop_head
  .width960.row
    .large-4.medium-4.small-4.columns.logo
      =link_to image_tag('logo.png'), root_path
    .clear-both
    .large-9.medium-9.small-9.columns.centered
      = form_tag landing_path, :method => 'get', :id => "search", :class=>'search-block centered ' do
        = text_field_tag :search, params[:search], class: 'search-field', placeholder: "Job Title"
        = text_field_tag :location, params[:location], class: 'search-field', placeholder: "Location (ZIP, city etc)"
        = submit_tag "Search", :name => nil, id: 'search'
        .clear-both
          = link_to 'Advanced Search', advanced_search_path, class: 'advanced-search right'

app/views/job/partials/_header_with_out_fixed_search.html.haml
.full-width_bg2#desktop_head.with_out_fixed
  .width960.row
    .large-4.medium-4.small-4.columns.logo
      =link_to image_tag('logo.png'), root_path
    .clear-both
    .large-9.medium-9.small-9.columns.centered
      = form_tag landing_path, :method => 'get', :id => "search", :class=>'search-block centered ' do
        = text_field_tag :search, params[:search], class: 'search-field', placeholder: "Job Title", required: "true"
        = text_field_tag :location, params[:location], class: 'search-field', placeholder: "Location (ZIP, city etc)"
        = submit_tag "Search", :name => nil, id: 'search'
        .clear-both
          = link_to 'Advanced Search', advanced_search_path, class: 'advanced-search right'

app/views/job/partials/_modal.html.haml
#openModal.modalDialog
  .div
    = image_tag('logo.png', class: 'modal-logo')
    %h2
      We've found
      %span.red
      -if @total_result_2.present?
        #{@total_result_2.to_s.gsub!("<tr>", "").gsub!("</tr>", "")}
      -else
        =render(text:'No result found')

      Jobs

    .modalDialog_inner
      %h3 How Is Employer Going To Contact You?
      %form.search-block#f1{action: "http://www.gogvo.com/subscribe.php", method: "post"}
        %input{name: "CampaignCode", type: "hidden", value: "504820539af8"}/
        %input{name: "FormId", type: "hidden", value: "3848419"}/
        %input{name: "AffiliateName", type: "hidden", value: "jobgoal"}/
        %input#Custom2{placeholder: "Last Name",name: "Custom2", onblur: "check(‘Custom2’, reg_Custom2)", onkeyup: "check(‘Custom2’, reg_Custom2)", type: "text"}/
        %input#Custom1{placeholder: "First Name",name: "Custom1", onblur: "check(‘Custom1’, reg_Custom1)", onkeyup: "check(‘Custom1’, reg_Custom1)", type: "text"}/
        %input#Email{placeholder: "E-Mail Adress",name: "Email", onblur: "check(‘Email’, reg_Email)", onkeyup: "check(‘Email’, reg_Email)", type: "text"}/
        .clear-both
        %input#modal_Dialog-button{type: "submit", value: "START SEARCH"}

        //%img{src: "http://www.gogvo.com/show_form.php?id=3848419"}/
        .clear-both
    %p By entering my information and clicking "Continue," I am providing express consent to be contacted by JobGoal.net  via email, phone and text, including my wireless phone number, regarding job openings, career services and educational opportunities using automated technology. Standard message and data rates may apply to text messages. You are not required to provide consent to receive services from JobGoal.net  I also understand that the JobGoal.net Privacy Policy  governs the collection of this information.

app/views/job/partials/_right_block.html.haml
.large-2.medium-2.small-2.column.right-sidebar
  = link_to 'Post a Job', post_job_path, class:'golden_button'
  %br
  - @posts.each  do |post|
    .right-sidebar_inner-block1
      %h4= link_to post.title, post_path(post)
      .time-ago
        %p.grey-light=post.created_at.to_formatted_s(:short)
  .right-sidebar_inner-block2
    <script async src="http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- 120x600, created 12/4/08 -->
    <ins class="adsbygoogle" style="display:inline-block;width:190px;height:600px" data-ad-client="ca-pub-7077183407169853" data-ad-slot="1189020219"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>

app/views/job/partials/_sorting.html.haml
.large-2.medium-2.small-2.column.left-sidebar
  .sort-by
  =form_tag sorting_path, :method => 'get', :id => "sorting_search" do
    %h4 Sort by
    = link_to 'Relavance desc',  :action => 'sorting', :sort_by => "rd"
    = link_to 'Relavance asc',  :action => 'sorting', :sort_by => "ra"
    %br
    = link_to 'Date desc',  :action => 'sorting', :sort_by => "dd"
    %br
    = link_to 'Date asc',  :action => 'sorting', :sort_by => "ad"
    .accordion
    %h4 Distance:
    = link_to 'Within 5 miles',  :action => 'sorting', :miles => "5"
    = link_to 'Within 10 miles',  :action => 'sorting', :miles => "10"
    = link_to 'Within 15 miles',  :action => 'sorting', :miles => "15"
    = link_to 'Within 25 miles',  :action => 'sorting', :miles => "25"
    = link_to 'Within 50 miles',  :action => 'sorting', :miles => "50"
    = link_to 'Within 100 miles',  :action => 'sorting', :miles => "100"
    %h4 Job Boards:
    %div
      = link_to 'Job Boards Only',  :action => 'sorting', :job_source => "job_board"
      = link_to 'Exclude Job Boards',  :action => 'sorting', :job_source => "primary"