config/routes.rb
Jobgoal::Application.routes.draw do

  get "ameriplan/sales-rep" => 'ameriplan#sales'
  get 'ameriplan/rssfeed'
  get "industry/forestry"
  get "industry/hunting"
  get "industry/automotive"
  get "industry/banking"
  get "industry/computing"
  get "industry/technology"
  get "industry/defense"
  get "industry/energy"
  get "industry/arts"
  get "industry/food"
  get "industry/health"
  get "industry/insurance"
  get "industry/manufacturing"
  get "industry/marketing"
  get "industry/media"
  get "industry/mining"
  get "industry/personal"
  get "industry/biotechnology"
  get "industry/services"
  get "industry/estate"
  get "industry/retail"
  get "industry/transportation"
  get "industry/travel"
  get "industry/waste"
  get "industry/remediation"

  get "states/alabama"
  get "states/alaska"
  get "states/arizona"
  get "states/arkansas"
  get "states/california"
  get "states/colorado"
  get "states/connecticut"
  get "states/delaware"
  get "states/florida"
  get "states/georgia"
  get "states/hawaii"
  get "states/idaho"
  get "states/illinois"
  get "states/indiana"
  get "states/iowa"
  get "states/kansas"
  get "states/kentucky"
  get "states/louisiana"
  get "states/maine"
  get "states/maryland"
  get "states/massachusetts"
  get "states/michigan"
  get "states/minnesota"
  get "states/mississippi"
  get "states/missouri"
  get "states/montana"
  get "states/nebraska"
  get "states/nevada"
  get "states/new_hampshire"
  get "states/new_mexico"
  get "states/new_jersey"
  get "states/new_york"
  get "states/north_carolina"
  get "states/north_dakota"
  get "states/ohio"
  get "states/oklahoma"
  get "states/pennsylvania"
  get "states/rhode_island"
  get "states/south_carolina"
  get "states/south_dakota"
  get "states/tennessee"
  get "states/texas"
  get "states/utah"
  get "states/vermont"
  get "states/virginia"
  get "states/washington"
  get "states/west_virginia"
  get "states/wisconsin"
  get "states/wyoming"

  devise_for :users



  mount RailsAdmin::Engine => '/job_goal_admin', :as => 'rails_admin'


  get 'landing' => 'job#landing'
  get 'home' => 'job#home', as: :home
  get 'contact' => 'job#contact', as: :contact

  root 'job#home'

  get "post_job" => 'job#post_job', as: :post_job



  get 'advanced_search' => 'job#advanced_search', as: :advanced_search
  get 'advanced_search_result' => 'job#advanced_search_result', as: :advanced_search_result

  get 'sorting' => 'job#sorting', as: :sorting
  get 'job_listing' => 'job#job_listing', as: :job_listing


  # Dinamic params

  get "post/:id", to: 'job#show', as: :post
  get "page/:id", to: 'job#show_page', as: :page


  get ':search/:location' => 'job#result' , as: :result, via: [:get]
  get ':search' => 'job#search_result' , as: :search_result, via: [:get]
  get '/location/:location' => 'job#location_result' , as: :location_result, via: [:get]
  get 'job/:search/:location' => 'job#next_result', as: :next_result, via: [:get]
end

app/controllers/job_controller.rb
require 'rubygems'
require 'open-uri'
require 'nokogiri'

class JobController < ApplicationController



  before_action :set_post, only: [:show]
  before_action :set_page, only: [:show_page]

  def landing
    @job_pages = JobPages.all
    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.order_by(order: :desc).limit(3)

    $search = params[:search]
    $location = params[:location]

    session[:search] = params[:search]
    session[:location] = params[:location]

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end

    if params[:location] == ''
      @search_finded = true
      redirect_to search_result_path(params[:search])
    elsif params[:search] == ''
      @search_finded = false
      redirect_to location_result_path(params[:location])
    elsif !params[:search].nil? && !params[:location].nil?
      redirect_to result_path(params[:search],params[:location])
    end

  end


  def search_result
    @job_pages = JobPages.all
    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.order_by(order: :desc).limit(3)

    session[:search] = params[:search]

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end


    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:search].to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @total_result_2 = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil?
      @total_result
    else
      @total_result = @total_result
    end
  end


  def location_result
    @job_pages = JobPages.all
    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.order_by(order: :desc).limit(3)

    session[:location] = params[:location]

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end


    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:location].to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @total_result_2 = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil?
      @total_result
    else
      @total_result = @total_result
    end
  end

  def home
    @job_pages = JobPages.all
    $search = params[:search]
    $location = params[:location]

    session[:search] = params[:search]
    session[:location] = params[:location]

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end

    if session[:search].nil?
      session[:search]=params[:search]
    else
      redirect_to result_path(params[:search],params[:location])
    end
  end

  def result
    @job_pages = JobPages.all
    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.order_by(order: :desc).limit(3)
    @jobpages = JobPages.all

    session[:search] = params[:search]
    session[:location] = params[:location]

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end

    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:search].to_s+"/l-"+session[:location].to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @total_result_2 = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil?
      @total_result
    else
      @total_result = @total_result
    end



  end

  def next_result
    @job_pages = JobPages.all
    session[:search] = params[:search]
    session[:location] = params[:location]


    if params[:page].present?
      @page = params[:page]
    end

    @posts = Post.all.order_by(created_at: :desc).limit(3)

    @advertising = Advertising.all.desc('order').limit(3)

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end

    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:search].to_s+"/l-"+session[:location].to_s+"/pn-"+@page.to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil? || @current_page_count.nil?
      render(text:'404')
    else
      render(text:'lol')
    end

    if @total_result.nil?
      @total_result
    end

  end




  def sorting
    @job_pages = JobPages.all
    if params[:sort_by].present?
      session[:sort_by] =params[:sort_by]
    end

    if params[:miles].present?
      session[:miles] =  params[:miles]
    end

    if params[:job_source].present?
      params[:job_source] = params[:job_source]
    end

    @posts = Post.all.order_by(created_at: :desc).limit(3)
    @advertising = Advertising.all.desc('order').limit(3)

    if session[:search].to_s.match(/\s/)
      session[:search] = session[:search].to_s.gsub!(" ", "+")
    end

    if session[:location].to_s.match(/\s/)
      session[:location] = session[:location].to_s.gsub!(" ", "+")
    end


    @url="http://api.simplyhired.com/a/jobs-api/xml-v2/q-"+session[:search].to_s+"/l-"+session[:location].to_s+"/pn-"+session[:page].to_s+"/sb-"+session[:sort_by].to_s+"/mi-"+session[:miles].to_s+"/fsr-"+session[:job_source].to_s+"?pshid=68487&ssty=2&cflg=r&jbd=jobgoal.jobamatic.com"

    @doc = Nokogiri::HTML(open(@url))
    @result = @doc.css("rs r").to_s
    @total_result = @doc.css("tr").to_s
    @current_page_count = @doc.css("si").to_s

    if @total_result.nil?
      @total_result
    else
      @total_result = @total_result
    end

    $page = params[:page]

    if $page.nil?
      $page='1'
    else
      # redirect_to 'http://www.simplyhired.com/k-'+$search+'-jobs.html'
      redirect_to next_result_path
    end
  end

  def advanced_search
    @job_pages = JobPages.all
    session[:search] = params[:search]
    session[:location] = params[:location]
   # With All Words
    #
    #
    #
    if params[:with_all_words].present?
      session[:with_all_words] = params[:with_all_words]+"+"

      if session[:with_all_words].to_s.match(/\s/)
        session[:with_all_words] = session[:with_all_words].to_s.gsub!(" ", "+AND+")
      end

    else
      session[:with_all_words] = ''
    end

    if params[:extract_phrase].present?
      session[:extract_phrase] = params[:extract_phrase]+"+"

      if  session[:extract_phrase].to_s.match(/\s/)
        session[:extract_phrase] =  session[:extract_phrase].to_s.gsub!(" ", "+")
      end

    else
      session[:extract_phrase] = ''
    end

    if params[:extract_phrase_company].present?
      session[:extract_phrase_company] = params[:extract_phrase_company]+"+"

      if session[:extract_phrase_company].to_s.match(/\s/)
        session[:extract_phrase_company] = session[:extract_phrase_company].to_s.gsub!(" ", "+")
      end

    else
      session[:extract_phrase_company] = ''
    end

    if params[:without_words].present?
      session[:without_words] = params[:without_words]+"+"

      if session[:without_words].to_s.match(/\s/)
        session[:without_words] = session[:without_words].to_s.gsub!(" ", "+NOT+")
      end

    else
      session[:without_words] = ''
    end

    if params[:least_one_of_words].present?
      session[:least_one_of_words] = params[:least_one_of_words]+"+"

      if session[:least_one_of_words].to_s.match(/\s/)
        session[:least_one_of_words] = session[:least_one_of_words].to_s.gsub!(" ", "+OR+")
      end
    else
      session[:least_one_of_words] = ''
    end

    if params[:state].present?
      session[:state] = params[:state]+"+"

     # if $least_one_of_words.to_s.match(/\s/)
     #   $least_one_of_words = $least_one_of_words.to_s.gsub!(" ", "+OR+")
     # end
    else
      session[:state] = ''
    end

    if params[:state_city].present?
      session[:state_city] = params[:state_city]+"+"

    # if $least_one_of_words.to_s.match(/\s/)
    #   $least_one_of_words = $least_one_of_words.to_s.gsub!(" ", "+OR+")
    # end

    if session[:state_city].to_s.match(/\s/)
      session[:state_city] = session[:state_city].to_s.gsub!(" ", "+")
    end
  else
    session[:state_city] = ''
  end

    if params[:state_zip].present?
      session[:state_zip] = params[:state_zip]+"+"

      # if $least_one_of_words.to_s.match(/\s/)
      #   $least_one_of_words = $least_one_of_words.to_s.gsub!(" ", "+OR+")
      # end

      if session[:state_zip].to_s.match(/\s/)
        session[:state_zip] = session[:state_zip].to_s.gsub!(" ", "+")
      end
    else
      session[:state_zip] = ''
    end

    if params[:miles].present?
      session[:miles] = params[:miles]

    else
      session[:miles] = ''
    end

    if params[:result_per_page].present?
      session[:result_per_page] = params[:result_per_page]

      else
        session[:result_per_page] = ''
      end

    if params[:sort_by_adv].present?
      session[:sort_by_adv] = params[:sort_by_adv]

    else
      session[:sort_by_adv] = ''
    end

app/helpers/job_helper.rb
module JobHelper
end

app/views/job/advanced_search.html.haml
#fb-root
.wrapper
  = render(partial:'job/partials/header')
  .content
    .width960.row.padding-0.bg-white
      .large-12.medium-12.small-12.column.advanced-search
        = form_tag advanced_search_path, :method => 'get', :id => "page" do


          .advanced-search_inner
            %h3.blue Job Categories
            %section
              .large-11.medium-11.small-11.column
                .search-block
                  = text_field_tag :with_all_words, params[:with_all_words], class: 'page-field', placeholder: "With at least one of the words"
                  = text_field_tag :extract_phrase, params[:extract_phrase], class: 'page-field', placeholder: "With extract phrase"
                  %input{type: "text", placeholder: "Within job title"}/
                  = text_field_tag :least_one_of_words, params[:least_one_of_words], class: 'page-field', placeholder: "With at least one of the words"
                  = text_field_tag :without_words, params[:without_words], class: 'page-field', placeholder: "Without the words"
                  = text_field_tag :extract_phrase_company, params[:extract_phrase_company], class: 'page-field', placeholder: "Within company name"

                  .clear-both
              .clear-both
          .advanced-search_inner
            %h3.blue Location
            %section
              .large-8.medium-8.small-8.column
                .search-block
                  = text_field_tag :state_city, params[:state_city], class: 'page-field', placeholder: "City"
                  = text_field_tag :state_zip, params[:state_zip], class: 'page-field', placeholder: "ZIP / postal code"
                  = select_tag :state, options_for_select([['Select State', ''], ['Alabama', 'AL'], ['Alaska', 'AK'], ['Arizona', 'AZ'], ['Arkansas', 'AR'], ['California', 'CA'], ['Colorado', 'CO'], ['Connecticut', 'CT'], ['District of Columbia', 'DC'], ['Delaware', 'DE'], ['Florida', 'FL'], ['Georgia', 'GA'], ['Hawaii', 'HI'],['Idaho', 'ID'], ['Illinois', 'IL'], ['Indiana', 'IN'], ['Iowa', 'IA'], ['Kansas', 'KS'], ['Kentucky', 'KY'], ['Lousiana', 'LA'], ['Maine', 'ME'], ['Maryland', 'MD'], ['Massachusetts', 'MA'], ['Michigan', 'MI'], ['Minnesota', 'MN'], ['Mississippi', 'MS'], ['Missouri', 'MO'], ['Montana', 'MT'], ['Nebraska', 'NE'], ['Nevada', 'NV'], ['New Hampshire', 'NH'], ['New Jersey', 'NJ'], ['New Mexico', 'NM'], ['New York', 'NY'], ['North Carolina', 'NC'], ['North Dakota', 'ND'], ['Ohio', 'OH'], ['Oklahoma', 'OK'], ['Oregon', 'OR'], ['Pennsylvania', 'PA'], ['Rhode Island', 'RI'], ['South Carolina', 'SC'], ['South Dakota', 'SD'], ['Tennessee', 'TN'], ['Texas', 'TX'], ['Utah', 'UT'], ['Vermont', 'VT'], ['Virginia', 'VA'], ['Washington', 'WA'], ['West Virginia', 'WV'], ['Wisconsin', 'WI'], ['Wyoming', 'WY']], params[:state])
                  = select_tag :miles, options_for_select([['Within Miles', ''], ['5 miles', '5'], ['10 miles', '10'], ['15 miles', '15'], ['25 miles', '25'], ['50 miles', '50'], ['100 miles', '100']], params[:miles])
                  .clear-both
              .clear-both
          .advanced-search_inner
            %h3.blue Preferences
            %section
              .large-8.medium-8.small-8.column
                .search-block
                  = select_tag :result_per_page, options_for_select([['10 results', '10'], ['15 results', '15'], ['25 results', '25'], ['50 results', '50']], params[:result_per_page])
                  = select_tag :sort_by_adv, options_for_select([['Relevance descending', 'rd'], ['Relevance ascending', 'ra'], ['Last seen date descending', 'dd'], ['Last seen date ascending', 'da'], ['Title descending', 'td'], ['Title ascending', 'ta'], ['Company descending', 'cd'], ['Company ascending', 'ca'], ['Location descending', 'ld'], ['Location ascending', 'la']], params[:sort_by_adv])
                  .clear-both
              .clear-both
          .advanced-search_inner
            .input-centered
              .search-block
                = submit_tag "SEARCH JOBS", :name => nil, id: 'page'
                %button.golden_button{type: "submit"} CLEAR
                .clear-both
  =render(partial: 'job/partials/footer')

app/views/job/contact.html.haml
:javascript
  if(window.location.href.substr(-2) !== "?r") {
    window.location = window.location.href + "?r";
  }

.wrapper
  = render(partial:'job/partials/header_with_out_fixed_search')
  .contact-form_block
    .row.width960.mt-150
      .large-8.medium-8.small-8.columns
        %h2 Contact Us Today
      .large-4.medium-4.small-4.columns.socials.right
        =link_to  image_tag('twitter.png'), 'http://twitter.com'
        =link_to  image_tag('facebook.png'), root_path
        =link_to  image_tag('linkedin.png'), root_path
        =link_to  image_tag('google.png'), root_path
        .fb-like{"data-action" => "like", "data-href" => "http://jobgoal.net", "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"}
      %hr/

      = form_tag contact_path, :method => 'get', :id => "contact" do

        .large-6.medium-4.small-6.columns.contact-form
          = text_field_tag :c_name, params[:c_name], class: 'page-field', placeholder: "Name",required: true, value: ''
          = email_field_tag :c_email, params[:c_email], class: 'page-field', placeholder: "Email", required: true, value: ''
          = text_field_tag :c_subject, params[:c_subject], class: 'page-field', placeholder: "Subject", required: true, value: ''
        .large-6.medium-4.small-6.columns.contact-form.right
          = text_area_tag :c_message, params[:c_message], class: 'page-field edot', placeholder: "Message"
          = recaptcha_tags
          = submit_tag 'SEND', :name => nil, id: 'contact'
  =render(partial: 'job/partials/footer')

app/views/job/home.html.haml
#fb-root
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_en/all.js#xfbml=1&appId=619667714730451";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
.wrapper
  .full-width_bg1
    .width960.row
      .large-4.medium-4.small-4.columns.logo
        =link_to  image_tag('logo.png'), root_path
      .large-2.medium-2.small-2.columns.right
        = link_to 'Post a Job', post_job_path, class: 'post-job right'
      .clear-both
      .large-9.medium-9.small-9.columns.centered
        %h1
          Over
          %span 6 Million Jobs
        %h2 Start Your Job Search Now
        = form_tag landing_path, :method => 'get', :id => "search", :class=>'search-block centered ' do
          = text_field_tag :search, params[:search], class: 'search-field', placeholder: "Job Title"
          = text_field_tag :location, params[:location], class: 'search-field', placeholder: "Location (ZIP, city etc)"
          = submit_tag "Search", :name => nil, id: 'search'
          .clear-both
          = link_to 'Advanced Search', advanced_search_path, class:'advanced-search right'
  .width960.row
    .large-12.medium-12.small-12.columns
      %p JobGoal.net provides the most up to date job listings available in your area. There are part-time and full-time positions you can apply for right now. Simply use our job search engine to access thousands job listings. Whether you're currently unemployed or looking for a change, we can help you find and reach your job goal!
      %hr
    .large-12.medium-12.small-12.columns.jobs-category
      %h3 Find Jobs by Category
      .large-3.medium-3.small-3.columns
        %ul

          %li
            =link_to 'Accounting',  :action => 'search_result', search: 'accounting'
            =link_to '/ Finance',  :action => 'search_result', search: 'finance'
          %li
            =link_to 'Internships',  :action => 'search_result', search: 'internships'
            =link_to '/ Clerical',  :action => 'search_result', search: 'clerical'
          %li
            =link_to 'Architecture',  :action => 'search_result', search: 'architecture'
            =link_to '/ Engineering',  :action => 'search_result', search: 'engineering'
          %li
            =link_to 'Art',  :action => 'search_result', search: 'art'
            =link_to '/ Graphic Design',  :action => 'search_result', search: 'graphic+design'
          %li
            =link_to 'Media',  :action => 'search_result', search: 'media'
            =link_to '/ Biotech',  :action => 'search_result', search: 'biotech'
          %li
            =link_to 'Science',  :action => 'search_result', search: 'science'
            =link_to '/ Computer',  :action => 'search_result', search: 'computer'
          %li
            =link_to 'Technology',  :action => 'search_result', search: 'technology'
            =link_to '/ Work From Home',  :action => 'search_result', search: 'work+from+home'
      .large-3.medium-3.small-3.columns
        %ul
          %li
            =link_to 'Customer Service',  :action => 'search_result', search: 'customer+service'
            =link_to '/ Executive',  :action => 'search_result', search: 'executive'
          
          %li
            =link_to 'Management',  :action => 'search_result', search: 'management'
            =link_to '/ Health Care',  :action => 'search_result', search: 'health+care'
          
          %li
            =link_to 'Nursing',  :action => 'search_result', search: 'nursing'
            =link_to '/ Human Resources',  :action => 'search_result', search: 'human+resources'
          
          %li
            =link_to 'Legal',  :action => 'search_result', search: 'legal'
            =link_to '/ Paralegal',  :action => 'search_result', search: 'paralegal'
          
          %li
            =link_to 'Marketing',  :action => 'search_result', search: 'marketing'
            =link_to '/ PR',  :action => 'search_result', search: 'pr'
          %li
            =link_to 'Advertising',  :action => 'search_result', search: 'advertising'
      .large-3.medium-3.small-3.columns
        %ul
          %li
            =link_to 'Nonprofit Jobs',  :action => 'search_result', search: 'nonprofit+jobs'
            =link_to '/ Volunteer',  :action => 'search_result', search: 'volunteer'
          
          %li
            =link_to 'Restaurant',  :action => 'search_result', search: 'restaurant'
            =link_to '/ Hotel',  :action => 'search_result', search: 'hotel'
          
          %li
            =link_to 'Retail',  :action => 'search_result', search: 'retail'
            =link_to '/ Sales',  :action => 'search_result', search: 'sales'
          
          %li
            =link_to 'Business Development',  :action => 'search_result', search: 'business+development'
            =link_to '/ Software',  :action => 'search_result', search: 'software'
          
          %li
            =link_to 'QA',  :action => 'search_result', search: 'qa'
            =link_to '/ Teaching',  :action => 'search_result', search: 'teaching'
      .large-3.medium-3.small-3.columns
        %ul
          %li
            =link_to 'Truck Driving',  :action => 'search_result', search: 'truck+driving'
            =link_to '/ Transportation',  :action => 'search_result', search: 'transportation'
          
          %li
            =link_to 'Logistics',  :action => 'search_result', search: 'logistics'
            =link_to '/ Writing',  :action => 'search_result', search: 'writing'
          
          %li
            =link_to 'Freelance Jobs',  :action => 'search_result', search: 'freelance+jobs'
            =link_to '/ Part-time Jobs',  :action => 'search_result', search: 'part-time+jobs'
          
          %li
            =link_to 'Temp Jobs',  :action => 'search_result', search: 'temp+jobs'
            =link_to '/ Summer Jobs',  :action => 'search_result', search: 'summer+jobs'
          
          %li
            =link_to 'Seasonal Work',  :action => 'search_result', search: 'seasonal+work'
            =link_to '/ Entry Level Positions',  :action => 'search_result', search: 'entry+level+positions'
      .clear-both
      =link_to 'Browse Job Listings >>', job_listing_path, class: 'browse-job-listings blue'
  =render(partial: 'job/partials/footer')

app/views/job/landing.html.haml
.wrapper
  .full-width_bg3
    .width960.row
      .large-4.medium-4.small-4.columns.logo
        =link_to  image_tag('logo.png'), root_path
      .clear-both
      .large-9.medium-9.small-9.columns.centered
        %h2 Search Jobs
        = form_tag landing_path, :method => 'get', :id => "search", :class=>'search-block centered ' do
          = text_field_tag :search, params[:search], class: 'search-field', placeholder: "Job Title", required: "true"
          = text_field_tag :location, params[:location], class: 'search-field', placeholder: "Location (ZIP, city etc)"
          = submit_tag "Search", :name => nil, id: 'search'
          .clear-both
  =render(partial: 'job/partials/footer')

app/views/job/post_job.html.haml
.wrapper
  =render(partial: 'job/partials/header_with_out_fixed_search')
  .w100p
    %iframe{:src=>"http://jobgoal.jobamatic.com/a/jbb/post-job", :frameborder=>"0", :width=>'900px', :height=>'1300px'}
  =render(partial: 'job/partials/footer')

app/views/job/show.html.haml
.wrapper
  =render(partial: 'job/partials/header_with_out_fixed_search')
  %h1.text-show=@post.title
  .text-show=simple_format(@post.content)
  =render(partial: 'job/partials/footer')

app/views/job/show_page.html.haml
.wrapper
  =render(partial: 'job/partials/header_with_out_fixed_search')
  %h1.text-show=@job_page.title
  .text-show=simple_format(@job_page.content)
  =render(partial: 'job/partials/footer')